version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: job_aggregator_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=job-aggregator
    volumes:
      - mongo_data:/data/db
    networks:
      - job-net

  redis:
    image: redis:alpine
    container_name: job_aggregator_redis
    ports:
      - "6379:6379"
    networks:
      - job-net

networks:
  job-net:
    driver: bridge

volumes:
  mongo_data:
